baseURL = "https://frdelib.org/"
canonifyURLs = true
languageCode = "en-us"
title = "Snail Knight"
description = "വാക്കിന്റെ വക്കിൽ"
theme = "PaperMod"
googleAnalytics = "G-X38629MW1Y"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false


[pagination]
  pagerSize = 12

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/posts/:year/:month/:slug/"

[params]
  hideSummary = true
  env = "production"
  customCSS = ["css/extended/mathbox.css"]
  defaultTheme = "auto"
  disableThemeToggle = false
  disableSpecial1stPost = true
  math = true

  ShowReadingTime = true
  ShowShareButtons = true
  shareButtons = ["twitter", "facebook", "whatsapp", "telegram", "reddit"]

  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  TocOpen = false

  mainSections = ["posts"]

  [params.katex]
    enable = true


[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 2
  [[menu.main]]
    name = "Search"
    url = "search/"
    weight = 3


[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
